env:
  browser: false
  es6: true
  jest: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint
  - plugin:prettier/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  process: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
  - prettier
rules:
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/interface-name-prefix': 0
  '@typescript-eslint/no-explicit-any': 1
  '@typescript-eslint/no-non-null-assertion': 0
  '@typescript-eslint/no-inferrable-types':
    - warn
    - ignoreParameters: true
  '@typescript-eslint/no-unused-vars': warn
  eol-last:
    - error
    - always
  import/no-unresolved: error
  import/order:
    - error
    - alphabetize:
        order: asc
      newlines-between: always
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  no-case-declarations: 0
  no-console: 0
  no-multi-spaces: error
  no-multiple-empty-lines:
    - error
    - max: 1
      maxEOF: 1
  prettier/prettier: error
  quotes:
    - error
    - single
  semi:
    - error
    - never
settings:
  import/resolver:
    typescript: {}
